@startuml
!include style.iuml
skinparam nodesep 16
skinparam ranksep 36
title Enemies
interface IDamageable {
  +TakeDamage(amount)
}
abstract class Enemy {
  #{abstract} StoppingDistance
  #{abstract} Attack(distance)
  #Animate(distance)
  #Die()
}
class MeleeEnemy <<Brute>>
class ShooterEnemy <<Sentinel>>
class DiverEnemy <<Glider>>
IDamageable <|.. Enemy
IDamageable <|.. PlayerHealth
Enemy <|-- MeleeEnemy
Enemy <|-- ShooterEnemy
Enemy <|-- DiverEnemy
@enduml
