skinparam dpi 200
skinparam shadowing false
skinparam monochrome true
skinparam defaultFontName "DejaVu Sans"
skinparam defaultFontSize 11
skinparam backgroundColor #FFFFFF
skinparam roundCorner 6
skinparam packageStyle rectangle
hide empty members
hide circle
